# Generated by Django 3.0.2 on 2020-02-03 03:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRDWLL', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('Primary', 'primary'), ('Secondary', 'secondary'), ('Success', 'success'), ('Danger', 'danger'), ('Warning', 'warning'), ('Info', 'info'), ('Light', 'light'), ('Dark', 'dark')], default='info', help_text='The style of the alert.', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='body',
            field=ckeditor.fields.RichTextField(help_text='The content that should be displayed for the alert.'),
        ),
    ]
