# Generated by Django 3.0.2 on 2020-02-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRDWLL', '0003_auto_20200203_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='body',
            field=models.TextField(help_text='The content that should be displayed for the alert.'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('alert alert-primary', 'Primary'), ('alert alert-secondary', 'Secondary'), ('alert alert-success', 'Success'), ('alert alert-danger', 'Danger'), ('alert alert-warning', 'Warning'), ('alert alert-info', 'Info'), ('alert alert-light', 'Light'), ('alert alert-dark', 'Dark')], help_text='The style of the alert.', max_length=32),
        ),
    ]
