# Generated by Django 3.0.2 on 2020-02-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRDWLL', '0005_alert_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='url',
            field=models.TextField(blank=True, help_text='Display the alert on a specified page.', null=True),
        ),
    ]
