# Generated by Django 3.0.2 on 2020-02-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRDWLL', '0006_auto_20200203_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='url',
            field=models.CharField(blank=True, help_text='Display the alert on a specified page.', max_length=512, null=True),
        ),
    ]
