# Generated by Django 3.1 on 2020-10-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRDWLL', '0008_auto_20200418_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(blank=True, default='', help_text='The title for the alert!', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('alert alert-success', 'Success'), ('alert alert-danger', 'Danger'), ('alert alert-warning', 'Warning'), ('alert alert-info', 'Info')], help_text='The style of the alert.', max_length=32),
        ),
    ]
