# Generated by Django 3.1 on 2020-11-01 17:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('TRDWLL', '0009_auto_20201023_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='body',
            field=tinymce.models.HTMLField(help_text='The content that should be displayed for the alert.'),
        ),
    ]
