# Generated by Django 3.1 on 2020-12-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRDWLL', '0012_auto_20201222_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='short_body',
            field=models.CharField(blank=True, default='', help_text='A short version of the body.', max_length=128, null=True),
        ),
    ]
