# Generated by Django 3.1 on 2020-12-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRDWLL', '0014_visitorpagehit_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorPageHit',
        ),
    ]
