# Generated by Django 2.2.1 on 2019-05-27 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the project', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='The version via 0.0.0.0 format.', max_length=32)),
                ('version_label', models.CharField(blank=True, help_text='The version label such as -beta or -rc.1.', max_length=32)),
                ('is_critical_update', models.BooleanField(default=False, help_text='Is this update a critical update?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPatchNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Added', 'Added'), ('Updated', 'Updated'), ('Fixed', 'Fixed'), ('Removed', 'Removed'), ('Security', 'Security')], max_length=20)),
                ('description', models.CharField(help_text='A brief description.', max_length=200)),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectVersion')),
            ],
        ),
    ]
