# Generated by Django 2.2.1 on 2019-05-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectversion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectversion',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
