# Generated by Django 2.2.1 on 2019-05-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190526_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='channel',
            field=models.CharField(choices=[('Stable', 'Stable'), ('Beta', 'Beta'), ('Alpha', 'Alpha')], default='Stable', help_text='What update channel is this version on?', max_length=32),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this update live?'),
        ),
        migrations.AlterField(
            model_name='projectpatchnote',
            name='category',
            field=models.CharField(choices=[('Added', 'Added'), ('Updated', 'Updated'), ('Fixed', 'Fixed'), ('Removed', 'Removed'), ('Deprecated', 'Deprecated'), ('Security', 'Security')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='version_label',
            field=models.CharField(blank=True, help_text='The version label such as alpha, beta, or rc.1.', max_length=32),
        ),
    ]
