# Generated by Django 2.2.1 on 2019-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190527_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='download_url',
            field=models.URLField(blank=True, help_text='Where can someone download this version?'),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='channel',
            field=models.CharField(choices=[('Stable', 'Stable'), ('Beta', 'Beta'), ('Alpha', 'Alpha'), ('Development', 'Development')], default='Stable', help_text='What update channel is this version on?', max_length=32),
        ),
    ]
