baseURL = 'https://test.trdwll.com/'
languageCode = 'en-us'
title = 'TRDWLL'
theme = 'anatole'

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
title = "Russ 'trdwll' Treadwell"
author = "Russ Treadwell"
description = """
I work on video games, websites, and general applications.
"""
profilePicture = "assets/russ_small.png"
mainSections = ["post"]
doNotLoadAnimations = true
singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"
copyright = """
2014-{{ YEAR }} Russ 'trdwll' Treadwell. All rights reserved. <br />
Made & Hosted in USA!
"""
oldContentWarning = true
oldContentDuration = 365
readMore = true
postSectionName = 'posts'
reversepagetitle = true

[permalinks]
  post = "/blog/:title"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/trdwll"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/trdwll/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://www.twitter.com/trdwll"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/trdwll"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:russ@trdwll.com"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"


# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
