# Generated by Django 3.0.2 on 2020-02-08 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPageHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the page was hit (viewed) for the first time.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When the page was hit (viewed) for the x time.')),
                ('page_url', models.URLField(help_text='The url that was accessed.')),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='The amount of times that the page has been accessed.')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the visitor viewed the site for the first time.')),
                ('ip_address', models.GenericIPAddressField(help_text='The IP address of the visitor.')),
                ('ip_country', models.CharField(help_text='The country location of the ip address.', max_length=100)),
                ('last_visit', models.DateTimeField(auto_now=True, help_text='The last time that the visitor visited the site.')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorPageHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(help_text='The url that was accessed.')),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='The amount of times that the page has been accessed by the visitor.')),
                ('visitor', models.ForeignKey(help_text='The visitor that has visited this page.', on_delete=django.db.models.deletion.CASCADE, to='analytics.Visitor')),
            ],
        ),
    ]
