# Generated by Django 3.0.2 on 2020-02-08 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorpagehit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the visitor viewed the page.'),
            preserve_default=False,
        ),
    ]
