# Generated by Django 3.2.9 on 2021-11-06 23:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Is this project public?')),
                ('title', models.CharField(help_text="What's the name of this product?", max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('release_date', models.DateTimeField()),
                ('keywords', models.CharField(blank=True, help_text='SEO keywords to help get more exposure.', max_length=512, null=True)),
                ('body', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Work Product',
                'verbose_name_plural': 'Work Products',
                'db_table': 'work_product',
                'ordering': ['-release_date'],
            },
        ),
    ]
