# Generated by Django 3.1 on 2020-11-21 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPageHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the page was hit (viewed) for the first time.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When the page was hit (viewed) for the x time.')),
                ('page_url', models.CharField(help_text='The url that was accessed.', max_length=200)),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='The amount of times that the page has been accessed.')),
            ],
            options={
                'db_table': 'analytics_globalpagehit',
                'ordering': ['-hit_count'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the visitor viewed the site for the first time.')),
                ('ip_address', models.GenericIPAddressField(help_text='The IP address of the visitor.')),
                ('ip_country', models.CharField(help_text='The country location of the ip address.', max_length=100)),
                ('user_agent', models.CharField(help_text='The useragent that the visitor is using.', max_length=300)),
                ('last_visit', models.DateTimeField(auto_now=True, help_text='The last time that the visitor visited the site.')),
            ],
            options={
                'db_table': 'analytics_visitor',
                'ordering': ['-last_visit'],
            },
        ),
        migrations.CreateModel(
            name='VisitorPageHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the visitor viewed the page.')),
                ('page_url', models.CharField(help_text='The url that was accessed.', max_length=200)),
                ('user_agent', models.TextField(help_text='The useragent that the visitor is using.')),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='The amount of times that the page has been accessed by the visitor.')),
                ('visitor', models.ForeignKey(help_text='The visitor that has visited this page.', on_delete=django.db.models.deletion.CASCADE, to='dashboard.visitor')),
            ],
            options={
                'db_table': 'analytics_visitorpagehit',
                'ordering': ['-created'],
            },
        ),
    ]
