# Generated by Django 3.1 on 2020-11-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_visitorpagehit_referer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorpagehit',
            name='hit_count',
        ),
        migrations.AddField(
            model_name='visitor',
            name='country_code',
            field=models.CharField(blank=True, default='', help_text='The country location of the ip address (country code).', max_length=16),
        ),
        migrations.AlterField(
            model_name='visitorpagehit',
            name='referer',
            field=models.CharField(blank=True, default='', help_text='The page that this visitor came from.', max_length=150),
        ),
    ]
