# Generated by Django 3.1 on 2020-11-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201121_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorpagehit',
            name='user_agent',
            field=models.CharField(help_text='The useragent that the visitor is using.', max_length=300),
        ),
    ]
