# Generated by Django 3.0.2 on 2020-01-23 14:37

import tinymce.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the category.', max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'blog_category',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField()),
                ('title', models.CharField(help_text='Title of the post.', max_length=200)),
                ('body', tinymce.models.HTMLField()),
                ('description', models.CharField(help_text='A short tagline that describes what the reader will be reading about.', max_length=100)),
                ('is_published', models.BooleanField(default=True, help_text='Do you want this post to be published publicly?')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='The category that the post will be listed under.', on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
            options={
                'db_table': 'blog_post',
            },
        ),
    ]
