# Generated by Django 2.2 on 2019-04-25 02:06

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the category.', max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'blog_category',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField()),
                ('title', models.CharField(help_text='Title of the post.', max_length=200)),
                ('body', models.TextField(help_text='The content of the post. (<strong>Markdown Supported</strong>)')),
                ('description', models.CharField(help_text='A short tagline that describes what the reader will be reading about.', max_length=100)),
                ('is_published', models.BooleanField(default=True, help_text='Do you want this post to be published publicly?')),
                ('image', models.ImageField()),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='The category that the post will be listed under.', on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'blog_post',
            },
        ),
    ]
