# Generated by Django 3.0.2 on 2020-02-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200125_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', help_text='A short description for the category.', max_length=200),
            preserve_default=False,
        ),
    ]
