# Generated by Django 3.0.2 on 2020-02-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200206_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', help_text='A short description for the category.', max_length=200),
            preserve_default=False,
        ),
    ]
