# Generated by Django 3.1 on 2020-10-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200418_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(default='', help_text='SEO keywords to help get more exposure.', max_length=512),
        ),
    ]
