# Generated by Django 3.1 on 2020-11-01 15:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201027_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_2',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
