# Generated by Django 3.1 on 2020-11-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_body_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_2',
        ),
    ]
