

SECRET_KEY = 'pp)6iq_^nw)7k_1%#@v%^srq!zqsvr+ed&rfzfkzi^2+i7h1np'

DEBUG = True

IPINFO_API_KEY = ''

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

POST_TO_TWITTER = False

TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_ACCESS_TOKEN_SECRET = ''